// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/elk_golang_compose/swagger/models"
)

// GetJSONSchemaJSONOKCode is the HTTP code returned for type GetJSONSchemaJSONOK
const GetJSONSchemaJSONOKCode int = 200

/*GetJSONSchemaJSONOK Poker Log Json Schema

swagger:response getJsonSchemaJsonOK
*/
type GetJSONSchemaJSONOK struct {

	/*
	  In: Body
	*/
	Payload *models.PokerTransaction `json:"body,omitempty"`
}

// NewGetJSONSchemaJSONOK creates GetJSONSchemaJSONOK with default headers values
func NewGetJSONSchemaJSONOK() *GetJSONSchemaJSONOK {

	return &GetJSONSchemaJSONOK{}
}

// WithPayload adds the payload to the get Json schema Json o k response
func (o *GetJSONSchemaJSONOK) WithPayload(payload *models.PokerTransaction) *GetJSONSchemaJSONOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Json schema Json o k response
func (o *GetJSONSchemaJSONOK) SetPayload(payload *models.PokerTransaction) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJSONSchemaJSONOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetJSONSchemaJSONInternalServerErrorCode is the HTTP code returned for type GetJSONSchemaJSONInternalServerError
const GetJSONSchemaJSONInternalServerErrorCode int = 500

/*GetJSONSchemaJSONInternalServerError Not Ok

swagger:response getJsonSchemaJsonInternalServerError
*/
type GetJSONSchemaJSONInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetJSONSchemaJSONInternalServerError creates GetJSONSchemaJSONInternalServerError with default headers values
func NewGetJSONSchemaJSONInternalServerError() *GetJSONSchemaJSONInternalServerError {

	return &GetJSONSchemaJSONInternalServerError{}
}

// WithPayload adds the payload to the get Json schema Json internal server error response
func (o *GetJSONSchemaJSONInternalServerError) WithPayload(payload *models.Error) *GetJSONSchemaJSONInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get Json schema Json internal server error response
func (o *GetJSONSchemaJSONInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetJSONSchemaJSONInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
