// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/elk_golang_compose/swagger/models"
)

// GetHealthV1OKCode is the HTTP code returned for type GetHealthV1OK
const GetHealthV1OKCode int = 200

/*GetHealthV1OK Service Health

swagger:response getHealthV1OK
*/
type GetHealthV1OK struct {

	/*
	  In: Body
	*/
	Payload string `json:"body,omitempty"`
}

// NewGetHealthV1OK creates GetHealthV1OK with default headers values
func NewGetHealthV1OK() *GetHealthV1OK {

	return &GetHealthV1OK{}
}

// WithPayload adds the payload to the get health v1 o k response
func (o *GetHealthV1OK) WithPayload(payload string) *GetHealthV1OK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health v1 o k response
func (o *GetHealthV1OK) SetPayload(payload string) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthV1OK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

// GetHealthV1InternalServerErrorCode is the HTTP code returned for type GetHealthV1InternalServerError
const GetHealthV1InternalServerErrorCode int = 500

/*GetHealthV1InternalServerError Not Ok

swagger:response getHealthV1InternalServerError
*/
type GetHealthV1InternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetHealthV1InternalServerError creates GetHealthV1InternalServerError with default headers values
func NewGetHealthV1InternalServerError() *GetHealthV1InternalServerError {

	return &GetHealthV1InternalServerError{}
}

// WithPayload adds the payload to the get health v1 internal server error response
func (o *GetHealthV1InternalServerError) WithPayload(payload *models.Error) *GetHealthV1InternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get health v1 internal server error response
func (o *GetHealthV1InternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetHealthV1InternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
