// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetHealthV1HandlerFunc turns a function with the right signature into a get health v1 handler
type GetHealthV1HandlerFunc func(GetHealthV1Params) middleware.Responder

// Handle executing the request and returning a response
func (fn GetHealthV1HandlerFunc) Handle(params GetHealthV1Params) middleware.Responder {
	return fn(params)
}

// GetHealthV1Handler interface for that can handle valid get health v1 params
type GetHealthV1Handler interface {
	Handle(GetHealthV1Params) middleware.Responder
}

// NewGetHealthV1 creates a new http.Handler for the get health v1 operation
func NewGetHealthV1(ctx *middleware.Context, handler GetHealthV1Handler) *GetHealthV1 {
	return &GetHealthV1{Context: ctx, Handler: handler}
}

/*GetHealthV1 swagger:route GET /health/v1 getHealthV1

GetHealthV1 get health v1 API

*/
type GetHealthV1 struct {
	Context *middleware.Context
	Handler GetHealthV1Handler
}

func (o *GetHealthV1) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetHealthV1Params()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
