// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi DATA TEAM API
DATA TEAM API


    Schemes:
      http
    Host: localhost:8000
    BasePath: /
    Version: v1

    Consumes:
    - application/json

    Produces:
    - application/json
    - text/plain

swagger:meta
*/
package restapi
