// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// PokerTransaction poker transaction
// swagger:model PokerTransaction
type PokerTransaction struct {

	// amount
	Amount int64 `json:"amount,omitempty"`

	// currency ID
	CurrencyID string `json:"currencyID,omitempty"`

	// playable
	Playable int64 `json:"playable,omitempty"`

	// playable before
	PlayableBefore int64 `json:"playableBefore,omitempty"`

	// player ID
	PlayerID string `json:"playerID,omitempty"`

	// player IP
	PlayerIP string `json:"playerIP,omitempty"`

	// transaction ID
	TransactionID string `json:"transactionID,omitempty"`
}

// Validate validates this poker transaction
func (m *PokerTransaction) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PokerTransaction) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PokerTransaction) UnmarshalBinary(b []byte) error {
	var res PokerTransaction
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
